### ISSUE TITLE
Clean 484E4441.bin missing for me

### ISSUE THREAD

**Issue by Guy77** [zoogie/Frogtool#6]
I didn't make a backup for the 484E4441.bin file (clean) anyone got any links to get it back (please, and thanks)

**Comment by zoogie** [comment]
This file is created automatically. You don't have to do anything, and you don't need to touch it.
If you deleted it, you can't just redownload it because it's console-unique.

You can still fix it IF you have cfw:
https://3ds.hacks.guide/troubleshooting.html#dsi--ds-functionality-is-broken-after-completing-the-guide
(you can skip section I: steps 4,6,7,8)

**Comment by zoogie** [comment]
Anyway, this is tech support, not a real issue with frogtool, so closing.
If you have further questions, please visit this discord:
https://discord.gg/C29hYvh
